# Run pylint. the rest of the linters are running in pre-commit ci
# but this does not work for pylint, thus we run it via Github Action
name: Pylint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: pylint --all-files
